name: Vars test

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-vars:
    runs-on: ubuntu-latest

    steps:
      - uses: ${{ vars.UNDEFINED_VAR == 'ticketOnly' && './actions/action_A' || './actions/action_B' }}
      - run: |
          echo "${{ (vars.UNDEFINED_VAR == 'ticketOnly' || vars.UNDEFINED_VAR == '') && 'Ticket only' || 'Conventional commit' }}"
